import Fastify from "fastify";
import fastifyStatic from "@fastify/static";
import {join} from "node:path";
import {fileURLToPath} from "node:url";
import cors from "@fastify/cors";
import {categories,tests} from "./data.js";
import {allQuestions,answerSession,createSession,getProgress,getQuestion,getSession,getTest,listSessions,soundEvents} from "./engine.js";
import {achievements,evaluateAchievements,levelFromXp,xpToNextLevel} from "./gamification.js";
import {about} from "./about.js";
import {register,login,getUserByToken} from "./auth.js";
import {getSnapshot,mergeSnapshot} from "./sync-store.js";

export function buildApp(){
 const app=Fastify({logger:true});
 app.register(cors,{origin:true});
 app.register(fastifyStatic,{root:join(fileURLToPath(new URL(".",import.meta.url)),"../public"),prefix:"/"});
 app.get("/api/v1/health",async()=>({status:"ok",service:"cogni-psicotecnico-api",version:"1.3.0"}));
 app.get("/api/v1/about",async()=>about);
 app.post("/api/v1/auth/register",async(req,res)=>{try{const b=req.body as any;return res.code(201).send(register(String(b.email??""),String(b.name??""),String(b.password??"")));}catch(e:any){return res.code(400).send({error:e.message});}});
 app.post("/api/v1/auth/login",async(req,res)=>{try{const b=req.body as any;return login(String(b.email??""),String(b.password??""));}catch(e:any){return res.code(401).send({error:e.message});}});
 app.get("/api/v1/auth/me",async(req,res)=>{const auth=req.headers.authorization||"";const token=auth.startsWith("Bearer ")?auth.slice(7):"";const user=getUserByToken(token);if(!user)return res.code(401).send({error:"UNAUTHORIZED"});return user;});
 app.get("/api/v1/sync/progress/:userId",async(req,res)=>{const snapshot=getSnapshot((req.params as any).userId);if(!snapshot)return res.code(404).send({error:"NO_SYNC_DATA"});return snapshot;});
 app.post("/api/v1/sync/progress/:userId",async(req)=>{const b=req.body as any;return mergeSnapshot((req.params as any).userId,{xp:Number(b.xp)||0,answered:Number(b.answered)||0,correct:Number(b.correct)||0,testsCompleted:Number(b.testsCompleted)||0,streak:Number(b.streak)||0});});
 app.get("/api/v1/categories",async()=>categories);
 app.get("/api/v1/levels",async()=>Array.from({length:10},(_,i)=>({level:i+1,xpRequired:i*500,title:i<2?"Iniciante":i<5?"Treinando":i<8?"Avançado":"Mestre"})));
 app.get("/api/v1/tests",async(req)=>{const q=req.query as {category?:string;level?:string;mode?:string};return tests.filter(t=>(!q.category||t.category===q.category)&&(!q.level||t.level===Number(q.level))&&(!q.mode||t.mode===q.mode));});
 app.get("/api/v1/tests/:id",async(req,res)=>{const t=getTest((req.params as any).id);if(!t)return res.code(404).send({error:"TEST_NOT_FOUND"});return t;});
 app.get("/api/v1/tests/:id/questions",async(req,res)=>{const t=getTest((req.params as any).id);if(!t)return res.code(404).send({error:"TEST_NOT_FOUND"});return t.questionIds.map(getQuestion).filter(Boolean).map(({answer,...safe}:any)=>safe);});
 app.get("/api/v1/questions/:id",async(req,res)=>{const q=getQuestion((req.params as any).id);if(!q)return res.code(404).send({error:"QUESTION_NOT_FOUND"});const {answer,...safe}=q;return safe;});
 app.post("/api/v1/sessions",async(req,res)=>{try{const b=req.body as any;return res.code(201).send(createSession(String(b.userId??"guest"),String(b.testId??"")));}catch(e:any){return res.code(400).send({error:e.message});}});
 app.post("/api/v1/sessions/:id/answers",async(req,res)=>{try{const b=req.body as any;return answerSession(String((req.params as any).id),String(b.questionId??""),String(b.answer??""));}catch(e:any){return res.code(400).send({error:e.message});}});
 app.get("/api/v1/sessions/:id",async(req,res)=>{const s=getSession((req.params as any).id);if(!s)return res.code(404).send({error:"SESSION_NOT_FOUND"});return s;});
 app.get("/api/v1/progress/:userId",async(req)=>{const p=getProgress((req.params as any).userId);return {...p,level:levelFromXp(p.xp),xpToNextLevel:xpToNextLevel(p.xp),achievements:evaluateAchievements(p)};});
 app.get("/api/v1/users/:userId/sessions",async(req)=>listSessions((req.params as any).userId));
 app.get("/api/v1/achievements",async()=>achievements);
 app.get("/api/v1/sound-events",async()=>soundEvents);
 app.get("/api/v1/stats",async()=>({questions:allQuestions().length,tests:tests.length,categories:categories.length,levels:10}));
 app.get("/",async(_req,res)=>res.sendFile("index.html"));
 return app;
}